/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.itausegdev.policies.schemas.insurance_policy_emitted;
@org.apache.avro.specific.AvroGenerated
public enum Category implements org.apache.avro.generic.GenericEnumSymbol<Category> {
  HOME, TRAVEL, PET, LIFE, AUTO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Category\",\"namespace\":\"br.itausegdev.policies.schemas.insurance_policy_emitted\",\"symbols\":[\"HOME\",\"TRAVEL\",\"PET\",\"LIFE\",\"AUTO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
