/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.itausegdev.policies.schemas.insurance_policy_emitted;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InsurancePolicyEmitted extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6853666354575702284L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InsurancePolicyEmitted\",\"namespace\":\"br.itausegdev.policies.schemas.insurance_policy_emitted\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"insurance_quote_id\",\"type\":\"long\"},{\"name\":\"product_id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"offer_id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"active\",\"type\":\"boolean\"},{\"name\":\"category\",\"type\":{\"type\":\"enum\",\"name\":\"Category\",\"symbols\":[\"HOME\",\"TRAVEL\",\"PET\",\"LIFE\",\"AUTO\"]}},{\"name\":\"created_at\",\"type\":{\"type\":\"long\",\"logicalType\":\"local-timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.LocalTimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<InsurancePolicyEmitted> ENCODER =
      new BinaryMessageEncoder<InsurancePolicyEmitted>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InsurancePolicyEmitted> DECODER =
      new BinaryMessageDecoder<InsurancePolicyEmitted>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InsurancePolicyEmitted> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InsurancePolicyEmitted> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InsurancePolicyEmitted> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InsurancePolicyEmitted>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InsurancePolicyEmitted to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InsurancePolicyEmitted from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InsurancePolicyEmitted instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InsurancePolicyEmitted fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private long insurance_quote_id;
  private java.lang.CharSequence product_id;
  private java.lang.CharSequence offer_id;
  private boolean active;
  private br.itausegdev.policies.schemas.insurance_policy_emitted.Category category;
  private java.time.LocalDateTime created_at;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InsurancePolicyEmitted() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param insurance_quote_id The new value for insurance_quote_id
   * @param product_id The new value for product_id
   * @param offer_id The new value for offer_id
   * @param active The new value for active
   * @param category The new value for category
   * @param created_at The new value for created_at
   */
  public InsurancePolicyEmitted(java.lang.Long id, java.lang.Long insurance_quote_id, java.lang.CharSequence product_id, java.lang.CharSequence offer_id, java.lang.Boolean active, br.itausegdev.policies.schemas.insurance_policy_emitted.Category category, java.time.LocalDateTime created_at) {
    this.id = id;
    this.insurance_quote_id = insurance_quote_id;
    this.product_id = product_id;
    this.offer_id = offer_id;
    this.active = active;
    this.category = category;
    this.created_at = created_at;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return insurance_quote_id;
    case 2: return product_id;
    case 3: return offer_id;
    case 4: return active;
    case 5: return category;
    case 6: return created_at;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.LocalTimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: insurance_quote_id = (java.lang.Long)value$; break;
    case 2: product_id = (java.lang.CharSequence)value$; break;
    case 3: offer_id = (java.lang.CharSequence)value$; break;
    case 4: active = (java.lang.Boolean)value$; break;
    case 5: category = (br.itausegdev.policies.schemas.insurance_policy_emitted.Category)value$; break;
    case 6: created_at = (java.time.LocalDateTime)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'insurance_quote_id' field.
   * @return The value of the 'insurance_quote_id' field.
   */
  public long getInsuranceQuoteId() {
    return insurance_quote_id;
  }


  /**
   * Sets the value of the 'insurance_quote_id' field.
   * @param value the value to set.
   */
  public void setInsuranceQuoteId(long value) {
    this.insurance_quote_id = value;
  }

  /**
   * Gets the value of the 'product_id' field.
   * @return The value of the 'product_id' field.
   */
  public java.lang.CharSequence getProductId() {
    return product_id;
  }


  /**
   * Sets the value of the 'product_id' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.CharSequence value) {
    this.product_id = value;
  }

  /**
   * Gets the value of the 'offer_id' field.
   * @return The value of the 'offer_id' field.
   */
  public java.lang.CharSequence getOfferId() {
    return offer_id;
  }


  /**
   * Sets the value of the 'offer_id' field.
   * @param value the value to set.
   */
  public void setOfferId(java.lang.CharSequence value) {
    this.offer_id = value;
  }

  /**
   * Gets the value of the 'active' field.
   * @return The value of the 'active' field.
   */
  public boolean getActive() {
    return active;
  }


  /**
   * Sets the value of the 'active' field.
   * @param value the value to set.
   */
  public void setActive(boolean value) {
    this.active = value;
  }

  /**
   * Gets the value of the 'category' field.
   * @return The value of the 'category' field.
   */
  public br.itausegdev.policies.schemas.insurance_policy_emitted.Category getCategory() {
    return category;
  }


  /**
   * Sets the value of the 'category' field.
   * @param value the value to set.
   */
  public void setCategory(br.itausegdev.policies.schemas.insurance_policy_emitted.Category value) {
    this.category = value;
  }

  /**
   * Gets the value of the 'created_at' field.
   * @return The value of the 'created_at' field.
   */
  public java.time.LocalDateTime getCreatedAt() {
    return created_at;
  }


  /**
   * Sets the value of the 'created_at' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.LocalDateTime value) {
    this.created_at = value;
  }

  /**
   * Creates a new InsurancePolicyEmitted RecordBuilder.
   * @return A new InsurancePolicyEmitted RecordBuilder
   */
  public static br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder newBuilder() {
    return new br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder();
  }

  /**
   * Creates a new InsurancePolicyEmitted RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InsurancePolicyEmitted RecordBuilder
   */
  public static br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder newBuilder(br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder other) {
    if (other == null) {
      return new br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder();
    } else {
      return new br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder(other);
    }
  }

  /**
   * Creates a new InsurancePolicyEmitted RecordBuilder by copying an existing InsurancePolicyEmitted instance.
   * @param other The existing instance to copy.
   * @return A new InsurancePolicyEmitted RecordBuilder
   */
  public static br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder newBuilder(br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted other) {
    if (other == null) {
      return new br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder();
    } else {
      return new br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder(other);
    }
  }

  /**
   * RecordBuilder for InsurancePolicyEmitted instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InsurancePolicyEmitted>
    implements org.apache.avro.data.RecordBuilder<InsurancePolicyEmitted> {

    private long id;
    private long insurance_quote_id;
    private java.lang.CharSequence product_id;
    private java.lang.CharSequence offer_id;
    private boolean active;
    private br.itausegdev.policies.schemas.insurance_policy_emitted.Category category;
    private java.time.LocalDateTime created_at;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.insurance_quote_id)) {
        this.insurance_quote_id = data().deepCopy(fields()[1].schema(), other.insurance_quote_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.product_id)) {
        this.product_id = data().deepCopy(fields()[2].schema(), other.product_id);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.offer_id)) {
        this.offer_id = data().deepCopy(fields()[3].schema(), other.offer_id);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.active)) {
        this.active = data().deepCopy(fields()[4].schema(), other.active);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.category)) {
        this.category = data().deepCopy(fields()[5].schema(), other.category);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.created_at)) {
        this.created_at = data().deepCopy(fields()[6].schema(), other.created_at);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing InsurancePolicyEmitted instance
     * @param other The existing instance to copy.
     */
    private Builder(br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.insurance_quote_id)) {
        this.insurance_quote_id = data().deepCopy(fields()[1].schema(), other.insurance_quote_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.product_id)) {
        this.product_id = data().deepCopy(fields()[2].schema(), other.product_id);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.offer_id)) {
        this.offer_id = data().deepCopy(fields()[3].schema(), other.offer_id);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.active)) {
        this.active = data().deepCopy(fields()[4].schema(), other.active);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.category)) {
        this.category = data().deepCopy(fields()[5].schema(), other.category);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.created_at)) {
        this.created_at = data().deepCopy(fields()[6].schema(), other.created_at);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'insurance_quote_id' field.
      * @return The value.
      */
    public long getInsuranceQuoteId() {
      return insurance_quote_id;
    }


    /**
      * Sets the value of the 'insurance_quote_id' field.
      * @param value The value of 'insurance_quote_id'.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder setInsuranceQuoteId(long value) {
      validate(fields()[1], value);
      this.insurance_quote_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'insurance_quote_id' field has been set.
      * @return True if the 'insurance_quote_id' field has been set, false otherwise.
      */
    public boolean hasInsuranceQuoteId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'insurance_quote_id' field.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder clearInsuranceQuoteId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'product_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductId() {
      return product_id;
    }


    /**
      * Sets the value of the 'product_id' field.
      * @param value The value of 'product_id'.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder setProductId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.product_id = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'product_id' field has been set.
      * @return True if the 'product_id' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'product_id' field.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder clearProductId() {
      product_id = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'offer_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getOfferId() {
      return offer_id;
    }


    /**
      * Sets the value of the 'offer_id' field.
      * @param value The value of 'offer_id'.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder setOfferId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.offer_id = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'offer_id' field has been set.
      * @return True if the 'offer_id' field has been set, false otherwise.
      */
    public boolean hasOfferId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'offer_id' field.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder clearOfferId() {
      offer_id = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'active' field.
      * @return The value.
      */
    public boolean getActive() {
      return active;
    }


    /**
      * Sets the value of the 'active' field.
      * @param value The value of 'active'.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder setActive(boolean value) {
      validate(fields()[4], value);
      this.active = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'active' field has been set.
      * @return True if the 'active' field has been set, false otherwise.
      */
    public boolean hasActive() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'active' field.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder clearActive() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'category' field.
      * @return The value.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.Category getCategory() {
      return category;
    }


    /**
      * Sets the value of the 'category' field.
      * @param value The value of 'category'.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder setCategory(br.itausegdev.policies.schemas.insurance_policy_emitted.Category value) {
      validate(fields()[5], value);
      this.category = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'category' field has been set.
      * @return True if the 'category' field has been set, false otherwise.
      */
    public boolean hasCategory() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'category' field.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder clearCategory() {
      category = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'created_at' field.
      * @return The value.
      */
    public java.time.LocalDateTime getCreatedAt() {
      return created_at;
    }


    /**
      * Sets the value of the 'created_at' field.
      * @param value The value of 'created_at'.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder setCreatedAt(java.time.LocalDateTime value) {
      validate(fields()[6], value);
      this.created_at = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'created_at' field has been set.
      * @return True if the 'created_at' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'created_at' field.
      * @return This builder.
      */
    public br.itausegdev.policies.schemas.insurance_policy_emitted.InsurancePolicyEmitted.Builder clearCreatedAt() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InsurancePolicyEmitted build() {
      try {
        InsurancePolicyEmitted record = new InsurancePolicyEmitted();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.insurance_quote_id = fieldSetFlags()[1] ? this.insurance_quote_id : (java.lang.Long) defaultValue(fields()[1]);
        record.product_id = fieldSetFlags()[2] ? this.product_id : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.offer_id = fieldSetFlags()[3] ? this.offer_id : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.active = fieldSetFlags()[4] ? this.active : (java.lang.Boolean) defaultValue(fields()[4]);
        record.category = fieldSetFlags()[5] ? this.category : (br.itausegdev.policies.schemas.insurance_policy_emitted.Category) defaultValue(fields()[5]);
        record.created_at = fieldSetFlags()[6] ? this.created_at : (java.time.LocalDateTime) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InsurancePolicyEmitted>
    WRITER$ = (org.apache.avro.io.DatumWriter<InsurancePolicyEmitted>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InsurancePolicyEmitted>
    READER$ = (org.apache.avro.io.DatumReader<InsurancePolicyEmitted>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










