spring:    
  data:
   mongodb:
    database: Cotacao
    host: localhost
    port: 27017
  kafka:
    properties:
      schema:
        registry:
          url: "http://localhost:8081"
    producer:
      bootstrap-servers: "localhost:9092"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      auto:register.schemas: true
      properties:
        enable.idempotence: true
    consumer:
      bootstrap-servers: "localhost:9092"
      group-id: "spring-boot-kafka-consumer"

server:
  port : 8090
  
catalog:
  service:
    endpoint: "http://localhost:8080/itausegdev-catalog/api/v1/"

topic:
  received:
    name: "itausegdev-insurance-quote-received"
  emitted:
    name: "itausegdev-insurance-policy-emitted"  